export const WHITE = "#ffffff"; // 하얀색
export const BLACK = "#000000";
export const SELECTBLACK = "#131313"; // 선택되엇을 때 표현되는 검은색
export const MEDIUMGRAY = "#A0A0A0"; // 중간 회색
export const LIGHTGRAY = "#F0F0F0"; // 밝은 회색
export const NEARWHITE = "#FAFAFA"; // 하얀색에 가까운 색
export const SIGNATURECOLOR = "#B39078"; // 시그니처 색상(갈색)
export const TERMSSTAR = "#C40000"; // 약관 동의 빨간색 아스트라 색상
export const NEARGRAY = "#AFAFAF";
export const REDCOLOR = "#C40000";
export const SkyBlue = "#1DA8FF";
export const DARKGRAY = "#505050";
export const LAVENDERPINK = "#F8A7F2";
export const LIGHTBEIGE = "#E0BDA5";
